In [45]:
import pandas as pd
import numpy as np
import glob
import os
import re
from sklearn.model_selection import train_test_split

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
dataset_path = "../../../DATASET_SCORE_TEST_EOI+2026/**/*.csv"
all_files = glob.glob(dataset_path, recursive=True)
# Filter: exclude files dengan nama diawali "MASTER_DATA_EOI"
pattern = re.compile(r"^MASTER_DATA_EOI")

filtered_files = [
    file for file in all_files if not pattern.match(os.path.basename(file))
]

df_list = []
for file in filtered_files:
    df_temp = pd.read_csv(file)
    df_list.append(df_temp)

# Gabungkan seluruh data
df_raw = pd.concat(df_list, ignore_index=True)

print(f"Total file ditemukan     : {len(all_files)}")
print(f"Total baris data awal    : {df_raw.shape[0]}")
df_raw.head()

Total file ditemukan     : 72
Total baris data awal    : 203141

,As At Month,Visa Type,Occupation,EOI Status,Count EOIs,English Test Score,State
0,2026-01-31,189PTS Points-Tested Stream,132211 Finance Manager,CLOSED,<20,0,ACT
1,2026-01-31,189PTS Points-Tested Stream,132511 Research and Development Manager,CLOSED,<20,0,ACT
2,2026-01-31,189PTS Points-Tested Stream,133111 Construction Project Manager,SUBMITTED,2100,0,ACT
3,2026-01-31,189PTS Points-Tested Stream,133111 Construction Project Manager,LODGED,223,0,ACT
4,2026-01-31,189PTS Points-Tested Stream,133111 Construction Project Manager,INVITED,<20,0,ACT

In [47]:
df_raw["Count EOIs"] = df_raw["Count EOIs"].replace("<20", 10)

In [48]:
df_raw["Count EOIs"] = df_raw["Count EOIs"].astype(int)

In [49]:
df_raw["EOI Status"].value_counts()

EOI Status
SUBMITTED    62361
CLOSED       60366
LODGED       37730
HOLD         26564
INVITED      16120
Name: count, dtype: int64

In [50]:
feature_cols = [
    col for col in df_raw.columns if col not in ["As At Month", "EOI Status"]
]

# Temukan duplikat berdasarkan fitur saja
duplicates = df_raw[df_raw.duplicated(subset=feature_cols, keep=False)]
print(f"Jumlah baris duplikat: {len(duplicates)}")
duplicates.sort_values(feature_cols)

Jumlah baris duplikat: 118734

,As At Month,Visa Type,Occupation,EOI Status,Count EOIs,English Test Score,State
8,2026-01-31,189PTS Points-Tested Stream,133211 Engineering Manager,LODGED,10,0,ACT
9,2026-01-31,189PTS Points-Tested Stream,133211 Engineering Manager,INVITED,10,0,ACT
10,2026-01-31,189PTS Points-Tested Stream,133211 Engineering Manager,HOLD,10,0,ACT
7818,2026-01-31,189PTS Points-Tested Stream,133211 Engineering Manager,LODGED,10,0,NSW
7819,2026-01-31,189PTS Points-Tested Stream,133211 Engineering Manager,INVITED,10,0,NSW
...,...,...,...,...,...,...,...
201266,2026-02-28,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,CLOSED,10,20,WA
203139,2026-03-31,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,10,20,WA
203140,2026-03-31,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,CLOSED,10,20,WA
129825,2026-03-31,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,SUBMITTED,23,10,VIC
129826,2026-03-31,491SNR State or Territory Nominated - Regional,639211 Retail Buyer,CLOSED,23,10,VIC

In [50]:
key_cols = ["Occupation", "Visa Type", "English Test Score", "Count EOIs","State"]


# Kumpulkan keys per status
lodged_keys = set(
    df_raw[df_raw["EOI Status"] == "LODGED"][key_cols].apply(tuple, axis=1)
)
closed_keys = set(
    df_raw[df_raw["EOI Status"] == "CLOSED"][key_cols].apply(tuple, axis=1)
)
invited_keys = set(
    df_raw[df_raw["EOI Status"] == "INVITED"][key_cols].apply(tuple, axis=1)
)
hold_keys = set(df_raw[df_raw["EOI Status"] == "HOLD"][key_cols].apply(tuple, axis=1))
submitted_keys = set(
    df_raw[df_raw["EOI Status"] == "SUBMITTED"][key_cols].apply(tuple, axis=1)
)

# lodged_or_invited_keys = lodged_keys | invited_keys  # gabungan


# Baris SUBMITTED/INVITED yang kombinasinya sudah ada di LODGED
mask_drop = df_raw["EOI Status"].isin(["SUBMITTED", "INVITED","HOLD"]) & df_raw[
    key_cols
].apply(tuple, axis=1).isin(lodged_keys)

mask_closed = (df_raw["EOI Status"] == "CLOSED") & df_raw[key_cols].apply(
    tuple, axis=1
).isin(lodged_keys)

mask_to_drop = mask_drop | mask_closed

#HAPUS KOMBINASI BARIS YANG SUDAH ADA DI LODGED

df_clean = df_raw[~mask_to_drop].reset_index(drop=True)




print(f"Sebelum : {len(df_raw):,} baris")
print(f"Dihapus : {mask_to_drop.sum():,} baris (SUBMITTED,INVITED,HOLD DAN CLOSED yang sudah LODGED)")
print(f"Sesudah : {len(df_clean):,} baris")
print(f"\nDistribusi EOI Status setelah cleaning:")
print(df_clean["EOI Status"].value_counts())

Sebelum : 203,141 baris
Dihapus : 69,230 baris (SUBMITTED,INVITED,HOLD DAN CLOSED yang sudah LODGED)
Sesudah : 133,911 baris

Distribusi EOI Status setelah cleaning:
EOI Status
SUBMITTED    44335
CLOSED       40617
LODGED       37730
HOLD          7383
INVITED       3846
Name: count, dtype: int64

In [127]:
df_raw.to_csv('df_raw.csv',index=False)

In [51]:
idx_to_drop = df_clean[df_clean["EOI Status"].isin(['SUBMITTED','HOLD','INVITED'])].index
df_clean = df_clean.drop(index=idx_to_drop).reset_index(drop=True)

In [52]:
df_clean = df_clean[
    df_clean["Visa Type"] != "491FSR Family Sponsored - Regional"
]

In [53]:
df_clean["EOI Status"] = df_clean["EOI Status"].replace({'CLOSED':'NOT LODGED'})

In [54]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 74315 entries, 0 to 78346
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   As At Month         74315 non-null  str
 1   Visa Type           74315 non-null  str
 2   Occupation          74315 non-null  str
 3   EOI Status          74315 non-null  str
 4   Count EOIs          74315 non-null  int64
 5   English Test Score  74315 non-null  int64
 6   State               74315 non-null  str
dtypes: int64(2), str(5)
memory usage: 4.5 MB

In [55]:
# ── Identifikasi 338 kombinasi ekstrem dari df_raw ───────────
combo_counts_raw = (
    df_clean.groupby(["Occupation", "English Test Score"])["EOI Status"]
    .agg(lodged=lambda x: (x == "LODGED").sum(), total="count")
    .reset_index()
)

combo_counts_raw["not_lodged"] = combo_counts_raw["total"] - combo_counts_raw["lodged"]
combo_counts_raw["type"] = combo_counts_raw.apply(
    lambda r: (
        "ALL NOT LODGED"
        if r["lodged"] == 0
        else ("ALL LODGED" if r["not_lodged"] == 0 else "MIXED")
    ),
    axis=1,
)

# ── Ambil hanya kombinasi MIXED ──────────────────────────────
mixed_combos = combo_counts_raw[combo_counts_raw["type"] == "MIXED"][
    ["Occupation", "English Test Score"]
]

In [56]:
# Cek kombinasi ekstrem yang dibuang
print("\nSample kombinasi ekstrem:")
print(
    combo_counts_raw[combo_counts_raw["type"] != "MIXED"][
        ["Occupation", "English Test Score", "lodged", "not_lodged", "total", "type"]
    ]
    .sort_values("total", ascending=False)
    .head(10)
    .to_string(index=False)
)

Sample kombinasi ekstrem:
                                        Occupation  English Test Score  lodged  not_lodged  total           type
             313211 Radiocommunications Technician                  10       0          60     60 ALL NOT LODGED
             313211 Radiocommunications Technician                  20       0          56     56 ALL NOT LODGED
             313211 Radiocommunications Technician                   0       0          56     56 ALL NOT LODGED
                     253512 Cardiothoracic Surgeon                  10       0          54     54 ALL NOT LODGED
                    211112 Dancer or Choreographer                  10       0          54     54 ALL NOT LODGED
                  134212 Nursing Clinical Director                  10       0          52     52 ALL NOT LODGED
                         254411 Nurse Practitioner                  10      48           0     48     ALL LODGED
254416 Registered Nurse (Developmental Disability)                   0      46           0     46     ALL LODGED
254416 Registered Nurse (Developmental Disability)                  10      46           0     46     ALL LODGED
                              234913 Meteorologist                  10      46           0     46     ALL LODGED

In [ ]:
# ── Filter df ────────────────────────────────────────────
df_clean = df_clean.merge(
    mixed_combos, on=["Occupation", "English Test Score"], how="inner"
)

# ── Laporan ──────────────────────────────────────────────────
print("=" * 50)
print("  HASIL FILTER df_raw")
print("=" * 50)
print(f"  Sebelum : {len(df_raw):,} baris")
print(f"  Sesudah : {len(df_clean):,} baris")
print(f"  Dibuang : {len(df_raw) - len(df_clean):,} baris")
print(
    f"\n  Kombinasi ekstrem dibuang : {(combo_counts_raw['type'] != 'MIXED').sum():,}"
)
print(f"  Kombinasi MIXED tersisa   : {(combo_counts_raw['type'] == 'MIXED').sum():,}")
print(
    f"\n  LODGED rate sebelum : {(df_raw['EOI Status'] == 'LODGED').mean() * 100:.2f}%"
)
print(
    f"  LODGED rate sesudah : {(df_clean['EOI Status'] == 'LODGED').mean() * 100:.2f}%"
)

In [57]:
# Cek Occupation yang tidak pernah LODGED 
occ_stats = df_raw.groupby("Occupation")["EOI Status"]\
.agg( lodged=lambda x: (x == "LODGED").sum(),total="count").reset_index()

occ_stats["not_lodged"] = occ_stats["total"] - occ_stats["lodged"]
occ_stats["lodged_pct"] = occ_stats["lodged"] / occ_stats["total"] * 100

# Filter yang tidak pernah LODGED
never_lodged = occ_stats[occ_stats["lodged"] == 0].sort_values("total", ascending=False)

In [58]:
never_lodged

,Occupation,lodged,total,not_lodged,lodged_pct
370,313211 Radiocommunications Technician,0,283,283,0.0
67,211112 Dancer or Choreographer,0,270,270,0.0
76,212315 Program Director (Television or Radio),0,244,244,0.0
68,211212 Music Director,0,234,234,0.0
97,222213 Stockbroking Dealer,0,223,223,0.0
...,...,...,...,...,...
131,231114 Helicopter Pilot,0,27,27,0.0
262,253515 Otorhinolaryngologist,0,27,27,0.0
277,254212 Nurse Researcher,0,27,27,0.0
382,322312 Pressure Welder,0,26,26,0.0
475,452314 Snowsport Instructor,0,24,24,0.0

In [22]:
never_lodged_list = never_lodged['Occupation'].tolist()

In [23]:
df_clean_filtered = df_clean[~df_clean["Occupation"].isin(never_lodged_list)]

In [58]:
print("\nSample kombinasi tersisa:")
print(
    combo_counts_raw[combo_counts_raw["type"] == "MIXED"][
        ["Occupation", "English Test Score", "lodged", "not_lodged", "total", "type"]
    ]
    .sort_values("total", ascending=False)
    .head(1000)
    .to_string(index=False)
)

Sample kombinasi tersisa:
                                                  Occupation  English Test Score  lodged  not_lodged  total  type
                              262112 ICT Security Specialist                  10      64          64    128 MIXED
                                 261111 ICT Business Analyst                  10      64          64    128 MIXED
                                 261111 ICT Business Analyst                  20      64          64    128 MIXED
                                    261313 Software Engineer                  10      64          64    128 MIXED
                                      261112 Systems Analyst                  10      64          64    128 MIXED
                                254499 Registered Nurses nec                  10      64          64    128 MIXED
                       312211 Civil Engineering Draftsperson                  10      64          64    128 MIXED
                                 221111 Accountant (General)                  20      64          64    128 MIXED
                                       233211 Civil Engineer                  10      64          64    128 MIXED
                                       233211 Civil Engineer                   0      64          64    128 MIXED
                                  233311 Electrical Engineer                  10      64          64    128 MIXED
                                  233311 Electrical Engineer                   0      64          64    128 MIXED
                             233914 Engineering Technologist                  10      64          64    128 MIXED
                                  233512 Mechanical Engineer                  20      64          64    128 MIXED
                                  233512 Mechanical Engineer                  10      64          64    128 MIXED
                                  233512 Mechanical Engineer                   0      64          64    128 MIXED
                                                 351311 Chef                  10      64          64    128 MIXED
                             233914 Engineering Technologist                  20      64          64    128 MIXED
                             241411 Secondary School Teacher                  10      64          64    128 MIXED
                             321211 Motor Mechanic (General)                  10      64          64    128 MIXED
                                 221111 Accountant (General)                  10      64          64    128 MIXED
                             233914 Engineering Technologist                   0      63          64    127 MIXED
                                  242111 University Lecturer                  10      63          64    127 MIXED
                                    261313 Software Engineer                  20      63          64    127 MIXED
                                 261312 Developer Programmer                  10      63          64    127 MIXED
                                     221213 External Auditor                  10      63          64    127 MIXED
                                  233311 Electrical Engineer                  20      63          64    127 MIXED
                                  242111 University Lecturer                  20      63          64    127 MIXED
                                       233211 Civil Engineer                  20      63          64    127 MIXED
                             321211 Motor Mechanic (General)                   0      64          62    126 MIXED
                                 233411 Electronics Engineer                  20      62          64    126 MIXED
                                                 351311 Chef                   0      64          62    126 MIXED
         241111 Early Childhood (Pre-primary School) Teacher                  10      64          62    126 MIXED
                       312211 Civil Engineering Draftsperson                  20      62          64    126 MIXED
                                 261111 ICT Business Analyst                   0      62          64    126 MIXED
                                 233411 Electronics Engineer                  10      62          64    126 MIXED
                                    233111 Chemical Engineer                  10      62          64    126 MIXED
            261399 Software and Applications Programmers nec                  10      62          63    125 MIXED
                                      261112 Systems Analyst                  20      62          63    125 MIXED
                       312211 Civil Engineering Draftsperson                   0      61          64    125 MIXED
                                    261313 Software Engineer                   0      61          64    125 MIXED
                        233999 Engineering Professionals nec                  10      62          63    125 MIXED
                                            232111 Architect                  10      62          62    124 MIXED
                                  242111 University Lecturer                   0      60          64    124 MIXED
                                    233111 Chemical Engineer                  20      60          63    123 MIXED
                                 221111 Accountant (General)                   0      59          64    123 MIXED
                                 233411 Electronics Engineer                   0      59          64    123 MIXED
                              262112 ICT Security Specialist                  20      59          64    123 MIXED
                                      261112 Systems Analyst                   0      59          64    123 MIXED
                              262112 ICT Security Specialist                   0      59          64    123 MIXED
                                 261312 Developer Programmer                  20      59          63    122 MIXED
                                 261312 Developer Programmer                   0      58          64    122 MIXED
                                            232111 Architect                  20      64          58    122 MIXED
                                                 351311 Chef                  20      63          59    122 MIXED
                                254499 Registered Nurses nec                  20      62          59    121 MIXED
                                    233111 Chemical Engineer                   0      57          64    121 MIXED
                               332211 Painting Trades Worker                  10      61          60    121 MIXED
                                            232111 Architect                   0      63          58    121 MIXED
                263111 Computer Network and Systems Engineer                  10      56          64    120 MIXED
                           254418 Registered Nurse (Medical)                  10      64          56    120 MIXED
                                  221113 Taxation Accountant                  10      56          64    120 MIXED
                         133111 Construction Project Manager                  10      56          64    120 MIXED
                                            331212 Carpenter                   0      63          56    119 MIXED
                                224711 Management Consultant                  10      60          59    119 MIXED
                         254412 Registered Nurse (Aged Care)                  10      63          56    119 MIXED
                          254424 Registered Nurse (Surgical)                  10      63          56    119 MIXED
                263111 Computer Network and Systems Engineer                  20      55          64    119 MIXED
                         133111 Construction Project Manager                  20      54          64    118 MIXED
                                              234211 Chemist                  10      54          64    118 MIXED
         241111 Early Childhood (Pre-primary School) Teacher                  20      61          57    118 MIXED
                                            331212 Carpenter                  10      61          57    118 MIXED
                                  233511 Industrial Engineer                  10      54          64    118 MIXED
                             321211 Motor Mechanic (General)                  20      62          55    117 MIXED
                          263311 Telecommunications Engineer                  10      53          64    117 MIXED
       254415 Registered Nurse (Critical Care and Emergency)                  10      61          56    117 MIXED
                         312212 Civil Engineering Technician                  10      53          64    117 MIXED
                                  233511 Industrial Engineer                  20      58          59    117 MIXED
                                    234212 Food Technologist                  10      54          62    116 MIXED
                        233999 Engineering Professionals nec                  20      54          62    116 MIXED
                               332211 Painting Trades Worker                   0      60          56    116 MIXED
                              234111 Agricultural Consultant                  10      52          64    116 MIXED
                         133111 Construction Project Manager                   0      51          64    115 MIXED
                        233999 Engineering Professionals nec                   0      53          62    115 MIXED
                                   261311 Analyst Programmer                  10      51          64    115 MIXED
                                        272511 Social Worker                  10      64          51    115 MIXED
                                          252711 Audiologist                  10      64          51    115 MIXED
                                      252511 Physiotherapist                  10      61          53    114 MIXED
                263111 Computer Network and Systems Engineer                   0      50          64    114 MIXED
            261399 Software and Applications Programmers nec                  20      53          61    114 MIXED
         241111 Early Childhood (Pre-primary School) Teacher                   0      61          53    114 MIXED
                                    233213 Quantity Surveyor                  10      50          64    114 MIXED
                                221112 Management Accountant                  10      50          64    114 MIXED
                                     221213 External Auditor                  20      52          62    114 MIXED
                                            331212 Carpenter                  20      61          53    114 MIXED
                                  233511 Industrial Engineer                   0      54          59    113 MIXED
                                       234517 Microbiologist                  10      60          53    113 MIXED
                          263311 Telecommunications Engineer                   0      49          64    113 MIXED
                                254499 Registered Nurses nec                   0      57          56    113 MIXED
                     254423 Registered Nurse (Perioperative)                  10      57          56    113 MIXED
                         312212 Civil Engineering Technician                  20      53          60    113 MIXED
                                    234212 Food Technologist                   0      54          58    112 MIXED
                         312212 Civil Engineering Technician                   0      48          64    112 MIXED
                           254418 Registered Nurse (Medical)                   0      61          51    112 MIXED
                  263312 Telecommunications Network Engineer                  10      48          64    112 MIXED
                                             232212 Surveyor                  10      52          60    112 MIXED
                                  233214 Structural Engineer                  10      49          63    112 MIXED
                                     221214 Internal Auditor                  10      48          64    112 MIXED
                                      234514 Biotechnologist                  10      52          59    111 MIXED
                               252411 Occupational Therapist                  10      60          50    110 MIXED
                             234312 Environmental Consultant                  10      60          50    110 MIXED
                233611 Mining Engineer (excluding Petroleum)                  10      49          61    110 MIXED
                                    233213 Quantity Surveyor                   0      48          62    110 MIXED
                                341111 Electrician (General)                  10      59          51    110 MIXED
                         234611 Medical Laboratory Scientist                  10      49          61    110 MIXED
                               233915 Environmental Engineer                  10      50          60    110 MIXED
                          263311 Telecommunications Engineer                  20      47          63    110 MIXED
                                  133211 Engineering Manager                  10      49          61    110 MIXED
                           254418 Registered Nurse (Medical)                  20      62          47    109 MIXED
                         233513 Production or Plant Engineer                  10      45          64    109 MIXED
                             241411 Secondary School Teacher                  20      56          53    109 MIXED
                                         224113 Statistician                  10      58          50    108 MIXED
                                              234211 Chemist                   0      49          59    108 MIXED
                                    234212 Food Technologist                  20      49          59    108 MIXED
            261399 Software and Applications Programmers nec                   0      54          53    107 MIXED
                               332211 Painting Trades Worker                  20      57          50    107 MIXED
                                     221213 External Auditor                   0      51          56    107 MIXED
                                            271311 Solicitor                  10      59          47    106 MIXED
                                   261311 Analyst Programmer                  20      43          63    106 MIXED
                                              234211 Chemist                  20      49          57    106 MIXED
                         233513 Production or Plant Engineer                   0      42          64    106 MIXED
                                     323211 Fitter (General)                  10      49          57    106 MIXED
                                   233112 Materials Engineer                  10      53          53    106 MIXED
                                    233213 Quantity Surveyor                  20      46          59    105 MIXED
                                341111 Electrician (General)                   0      62          43    105 MIXED
                233611 Mining Engineer (excluding Petroleum)                  20      54          51    105 MIXED
                233611 Mining Engineer (excluding Petroleum)                   0      47          58    105 MIXED
                                   261311 Analyst Programmer                   0      44          60    104 MIXED
                                139912 Environmental Manager                  10      52          52    104 MIXED
                                224711 Management Consultant                  20      49          55    104 MIXED
                                 322313 Welder (First Class)                  10      50          54    104 MIXED
                             241411 Secondary School Teacher                   0      54          50    104 MIXED
                                   233612 Petroleum Engineer                  10      52          52    104 MIXED
                         233513 Production or Plant Engineer                  20      40          63    103 MIXED
                              234111 Agricultural Consultant                   0      43          60    103 MIXED
                                233911 Aeronautical Engineer                  10      43          60    103 MIXED
                         254412 Registered Nurse (Aged Care)                   0      56          47    103 MIXED
                    312312 Electrical Engineering Technician                  10      42          60    102 MIXED
                  312311 Electrical Engineering Draftsperson                  10      56          46    102 MIXED
                        323214 Metal Machinist (First Class)                  10      47          55    102 MIXED
                                            224311 Economist                  10      45          57    102 MIXED
                             234511 Life Scientist (General)                  10      48          54    102 MIXED
                             234312 Environmental Consultant                  20      61          41    102 MIXED
                                           331111 Bricklayer                  10      57          44    101 MIXED
                               234112 Agricultural Scientist                  10      53          48    101 MIXED
                              232214 Other Spatial Scientist                  10      59          42    101 MIXED
                                    334111 Plumber (General)                  10      55          46    101 MIXED
       254415 Registered Nurse (Critical Care and Emergency)                   0      50          51    101 MIXED
                   342313 Electronic Equipment Trades Worker                  10      44          57    101 MIXED
                                         224113 Statistician                  20      57          44    101 MIXED
                                261211 Multimedia Specialist                  10      43          57    100 MIXED
                                      234514 Biotechnologist                  20      46          54    100 MIXED
                                             232212 Surveyor                   0      42          58    100 MIXED
                                     322311 Metal Fabricator                  10      52          48    100 MIXED
                                224711 Management Consultant                   0      51          49    100 MIXED
                     234313 Environmental Research Scientist                  10      51          49    100 MIXED
                                  233913 Biomedical Engineer                  10      40          60    100 MIXED
                                221112 Management Accountant                  20      38          62    100 MIXED
                                 333411 Wall and Floor Tiler                  10      55          44     99 MIXED
                                      132211 Finance Manager                  10      43          56     99 MIXED
                                  233214 Structural Engineer                  20      41          58     99 MIXED
                              234111 Agricultural Consultant                  20      42          57     99 MIXED
                               233915 Environmental Engineer                  20      47          52     99 MIXED
                  263312 Telecommunications Network Engineer                   0      43          56     99 MIXED
                  263312 Telecommunications Network Engineer                  20      41          58     99 MIXED

In [55]:
from sklearn.preprocessing import LabelEncoder,StandardScaler


df_model = df_clean.copy()
le_occ = LabelEncoder()
Standardize = StandardScaler()
df_model = pd.get_dummies(df_model, columns=["Visa Type", "State"], dtype=int)
df_model["occupation_enc"] = le_occ.fit_transform(df_model["Occupation"])
df_model["Status_enc"]  = df_model['EOI Status'].map(
    {
        "LODGED": 1,  
        "NOT LODGED": 0
    }
)
drop_cols = ["Occupation", "As At Month", "EOI Status", "Status_enc"]
feature_cols = [c for c in df_model.columns if c not in drop_cols]

In [56]:
df_model['Occupation'].nunique()

484

In [57]:
df_model['EOI Status'].value_counts()

EOI Status
NOT LODGED    38097
LODGED        36218
Name: count, dtype: int64

In [60]:
feature_cols

['Count EOIs',
 'English Test Score',
 'Visa Type_189PTS Points-Tested Stream',
 'Visa Type_190SAS Skilled Australian Sponsored',
 'Visa Type_491SNR State or Territory Nominated - Regional',
 'State_ACT',
 'State_NSW',
 'State_NT',
 'State_QLD',
 'State_SA',
 'State_TAS',
 'State_VIC',
 'State_WA',
 'occupation_enc']

In [61]:
df_model[feature_cols].info()

<class 'pandas.DataFrame'>
Index: 74315 entries, 0 to 78346
Data columns (total 14 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Count EOIs                                                74315 non-null  int64
 1   English Test Score                                        74315 non-null  int64
 2   Visa Type_189PTS Points-Tested Stream                     74315 non-null  int64
 3   Visa Type_190SAS Skilled Australian Sponsored             74315 non-null  int64
 4   Visa Type_491SNR State or Territory Nominated - Regional  74315 non-null  int64
 5   State_ACT                                                 74315 non-null  int64
 6   State_NSW                                                 74315 non-null  int64
 7   State_NT                                                  74315 non-null  int64
 8   State_QLD                                                 74315 non-null  int64
 9   State_SA                                                  74315 non-null  int64
 10  State_TAS                                                 74315 non-null  int64
 11  State_VIC                                                 74315 non-null  int64
 12  State_WA                                                  74315 non-null  int64
 13  occupation_enc                                            74315 non-null  int64
dtypes: int64(14)
memory usage: 8.5 MB

In [62]:
df_model['Occupation']

0                         132211 Finance Manager
1        132511 Research and Development Manager
2            133111 Construction Project Manager
3            133111 Construction Project Manager
4                     133211 Engineering Manager
                          ...
78342      452311 Diving Instructor (Open Water)
78343              511111 Contract Administrator
78344    511112 Program or Project Administrator
78345    511112 Program or Project Administrator
78346                        639211 Retail Buyer
Name: Occupation, Length: 74315, dtype: str

In [63]:
X = df_model[feature_cols]
y = df_model["Status_enc"]

In [64]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [65]:
from sklearn.metrics import (
    f1_score,
    roc_auc_score,
    classification_report,
)

In [66]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

In [67]:
# SMOTE hanya di training set
rus = SMOTE(random_state=42)
X_train_bal, y_train_bal = rus.fit_resample(X_train, y_train)
print(f"Train sebelum: {pd.Series(y_train).value_counts().to_dict()}")
print(f"Train sesudah: {pd.Series(y_train_bal).value_counts().to_dict()}")
print(f"Test (tidak diubah): {pd.Series(y_test).value_counts().to_dict()}")

Train sebelum: {0: 30523, 1: 28929}
Train sesudah: {0: 30523, 1: 30523}
Test (tidak diubah): {0: 7574, 1: 7289}

In [68]:
from xgboost import XGBClassifier

# Handle imbalance
scale_pos_weight = (y_train_bal == 1).sum() / (y_train_bal == 0).sum()

# Train model
model = XGBClassifier(
    n_estimators=900,
    max_depth=9,
    learning_rate=0.06,
    subsample=1,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1,
)

In [69]:
model.fit(
    X_train_bal,
    y_train_bal
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.06, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=9,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=900,
              n_jobs=-1, num_parallel_tree=None, ...)

In [70]:
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.90      0.91      7574
           1       0.90      0.92      0.91      7289

    accuracy                           0.91     14863
   macro avg       0.91      0.91      0.91     14863
weighted avg       0.91      0.91      0.91     14863

In [71]:
from sklearn.metrics import f1_score

# Cek gap train vs test
train_f1 = f1_score(y_train, model.predict(X_train))
test_f1 = f1_score(y_test, model.predict(X_test))
print(f"Train F1 : {train_f1:.3f}")
print(f"Test  F1 : {test_f1:.3f}")
print(f"Gap      : {train_f1 - test_f1:.3f}")

Train F1 : 0.943
Test  F1 : 0.911
Gap      : 0.032

In [124]:
import joblib
joblib.dump(le_occ, "encoder_occupation.joblib")

['encoder_occupation.joblib']

In [42]:
# Tabel mapping lengkap
mapping = pd.DataFrame(
    {"occupation": le_occ.classes_, "encoded": range(len(le_occ.classes_))}
)

pd.set_option("display.max_rows", None)
print(mapping.to_string(index=False))
pd.reset_option("display.max_rows")

                                                  occupation  encoded
                                   121111 Aquaculture Farmer        0
                                        121211 Cotton Grower        1
                                        121212 Flower Grower        2
                                  121213 Fruit or Nut Grower        3
                     121214 Grain, Oilseed or Pasture Grower        4
                                         121215 Grape Grower        5
                                    121216 Mixed Crop Farmer        6
                                    121217 Sugar Cane Grower        7
                                     121221 Vegetable Grower        8
                                     121299 Crop Farmers nec        9
                                             121311 Apiarist       10
                                   121312 Beef Cattle Farmer       11
                                  121313 Dairy Cattle Farmer       12
                                        121316 Horse Breeder       13
                               121317 Mixed Livestock Farmer       14
                                       121321 Poultry Farmer       15
                                121399 Livestock Farmers nec       16
                      121411 Mixed Crop and Livestock Farmer       17
                          131112 Sales and Marketing Manager       18
                                  131113 Advertising Manager       19
                             131114 Public Relations Manager       20
                           132111 Corporate Services Manager       21
                                      132211 Finance Manager       22
                               132311 Human Resource Manager       23
                          132411 Policy and Planning Manager       24
                     132511 Research and Development Manager       25
                         133111 Construction Project Manager       26
                                      133112 Project Builder       27
                                  133211 Engineering Manager       28
                                         133411 Manufacturer       29
                        133511 Production Manager (Forestry)       30
                   133512 Production Manager (Manufacturing)       31
                          133513 Production Manager (Mining)       32
                      133611 Supply and Distribution Manager       33
                                  133612 Procurement Manager       34
                            134111 Child Care Centre Manager       35
                                134211 Medical Administrator       36
                            134212 Nursing Clinical Director       37
                  134213 Primary Health Organisation Manager       38
                               134214 Welfare Centre Manager       39
             134299 Health and Welfare Services Managers nec       40
                                     134311 School Principal       41
                           134412 Regional Education Manager       42
                               134499 Education Managers nec       43
                                  135112 ICT Project Manager       44
                                     135199 ICT Managers nec       45
                        139911 Arts Administrator or Manager       46
                                139912 Environmental Manager       47
                                   139913 Laboratory Manager       48
                            139914 Quality Assurance Manager       49
                                 139915 Sports Administrator       50
                              139999 Specialist Managers nec       51
                           141111 Cafe or Restaurant Manager       52
              141211 Caravan Park and Camping Ground Manager       53
                               141311 Hotel or Motel Manager       54
           141999 Accommodation and Hospitality Managers nec       55
                                  142115 Post Office Manager       56
                             149111 Amusement Centre Manager       57
                               149112 Fitness Centre Manager       58
                                149113 Sports Centre Manager       59
                             149212 Customer Service Manager       60
                       149311 Conference and Event Organiser       61
                            149413 Transport Company Manager       62
                                   149913 Facilities Manager       63
                 149914 Financial Institution Branch Manager       64
                              211112 Dancer or Choreographer       65
                                       211212 Music Director       66
                              211213 Musician (Instrumental)       67
                              211299 Music Professionals nec       68
                                         211311 Photographer       69
                                    212111 Artistic Director       70
                                212212 Book or Script Editor       71
          212312 Director (Film, Television, Radio or Stage)       72
                                212314 Film and Video Editor       73
               212315 Program Director (Television or Radio)       74
                                        212316 Stage Manager       75
                                   212317 Technical Director       76
                                       212318 Video Producer       77
                                           212411 Copywriter       78
                       212412 Newspaper or Periodical Editor       79
                                     212413 Print Journalist       80
                                     212415 Technical Writer       81
                                212416 Television Journalist       82
                    212499 Journalists and Other Writers nec       83
                                 221111 Accountant (General)       84
                                221112 Management Accountant       85
                                  221113 Taxation Accountant       86
                                    221211 Company Secretary       87
                                     221213 External Auditor       88
                                     221214 Internal Auditor       89
                                   222111 Commodities Trader       90
                                       222112 Finance Broker       91
                                     222113 Insurance Broker       92
                                222199 Financial Brokers nec       93
                              222211 Financial Market Dealer       94
                                  222213 Stockbroking Dealer       95
                                222299 Financial Dealers nec       96
                         222311 Financial Investment Adviser       97
                         222312 Financial Investment Manager       98
                               223111 Human Resource Adviser       99
                               223112 Recruitment Consultant      100
                          223113 Workplace Relations Adviser      101
                                          223211 ICT Trainer      102
                                              224111 Actuary      103
                                        224112 Mathematician      104
                                         224113 Statistician      105
                            224212 Gallery or Museum Curator      106
                           224213 Health Information Manager      107
                                      224214 Records Manager      108
                                            224311 Economist      109
                                       224412 Policy Analyst      110
                                       224511 Land Economist      111
                                               224512 Valuer      112
                                            224611 Librarian      113
                                224711 Management Consultant      114
                     224712 Organisation and Methods Analyst      115
                                      224912 Liaison Officer      116
                                     224914 Patents Examiner      117
       224999 Information and Organisation Professionals nec      118
                               225111 Advertising Specialist      119
                              225112 Market Research Analyst      120
                                 225113 Marketing Specialist      121
                                  225211 ICT Account Manager      122
                     225212 ICT Business Development Manager      123
                             225213 ICT Sales Representative      124
                        225311 Public Relations Professional      125
                  225499 Technical Sales Representatives nec      126
                                      231111 Aeroplane Pilot      127
                                    231113 Flying Instructor      128
                                        231213 Ship's Master      129
                                            232111 Architect      130
                                  232112 Landscape Architect      131
                                             232212 Surveyor      132
                                         232213 Cartographer      133
                              232214 Other Spatial Scientist      134
                                     232311 Fashion Designer      135
                                  232312 Industrial Designer      136
                                   232313 Jewellery Designer      137
                                     232411 Graphic Designer      138
                                          232412 Illustrator      139
                                  232413 Multimedia Designer      140
                                         232414 Web Designer      141
                                    232511 Interior Designer      142
                           232611 Urban and Regional Planner      143
                                    233111 Chemical Engineer      144
                                   233112 Materials Engineer      145
                                       233211 Civil Engineer      146
                                233212 Geotechnical Engineer      147
                                    233213 Quantity Surveyor      148
                                  233214 Structural Engineer      149
                                   233215 Transport Engineer      150
                                  233311 Electrical Engineer      151
                                 233411 Electronics Engineer      152
                                  233511 Industrial Engineer      153
                                  233512 Mechanical Engineer      154
                         233513 Production or Plant Engineer      155
                233611 Mining Engineer (excluding Petroleum)      156
                                   233612 Petroleum Engineer      157
                                233911 Aeronautical Engineer      158
                                233912 Agricultural Engineer      159
                                  233913 Biomedical Engineer      160
                             233914 Engineering Technologist      161
                               233915 Environmental Engineer      162
                                      233916 Naval Architect      163
                        233999 Engineering Professionals nec      164
                              234111 Agricultural Consultant      165
                               234112 Agricultural Scientist      166
                                             234113 Forester      167
                                              234211 Chemist      168
                                    234212 Food Technologist      169
                                           234213 Wine Maker      170
                                 234311 Conservation Officer      171
                             234312 Environmental Consultant      172
                     234313 Environmental Research Scientist      173
                         234399 Environmental Scientists nec      174
                                            234411 Geologist      175
                                         234412 Geophysicist      176
                                       234413 Hydrogeologist      177
                             234511 Life Scientist (General)      178
                                           234513 Biochemist      179
                                      234514 Biotechnologist      180
                                             234515 Botanist      181
                                     234516 Marine Biologist      182
                                       234517 Microbiologist      183
                                            234518 Zoologist      184
                                  234599 Life Scientists nec      185
                         234611 Medical Laboratory Scientist      186
                                         234711 Veterinarian      187
                                          234911 Conservator      188
                                         234912 Metallurgist      189
                                        234913 Meteorologist      190
                                            234914 Physicist      191
                                234915 Exercise Physiologist      192
       234999 Natural and Physical Science Professionals nec      193
         241111 Early Childhood (Pre-primary School) Teacher      194
                               241213 Primary School Teacher      195
                                241311 Middle School Teacher      196
                             241411 Secondary School Teacher      197
                                241511 Special Needs Teacher      198
                      241512 Teacher of the Hearing Impaired      199
                        241513 Teacher of the Sight Impaired      200
                       241599 Special Education Teachers nec      201
                                  242111 University Lecturer      202
                         242211 Vocational Education Teacher      203
                                    249111 Education Adviser      204
                        249211 Art Teacher (Private Tuition)      205
                      249212 Dance Teacher (Private Tuition)      206
                      249214 Music Teacher (Private Tuition)      207
                      249299 Private Tutors and Teachers nec      208
    249311 Teacher of English to Speakers of Other Languages      209
                                            251111 Dietitian      210
                                         251112 Nutritionist      211
                      251211 Medical Diagnostic Radiographer      212
                          251212 Medical Radiation Therapist      213
                        251213 Nuclear Medicine Technologist      214
                                          251214 Sonographer      215
                         251311 Environmental Health Officer      216
               251312 Occupational Health and Safety Adviser      217
                                          251411 Optometrist      218
                                           251412 Orthoptist      219
                                  251511 Hospital Pharmacist      220
                                251512 Industrial Pharmacist      221
                                    251513 Retail Pharmacist      222
                             251911 Health Promotion Officer      223
                             251912 Orthotist or Prosthetist      224
    251999 Health Diagnostic and Promotion Professionals nec      225
                                         252111 Chiropractor      226
                                            252112 Osteopath      227
                                        252211 Acupuncturist      228
                                           252213 Naturopath      229
            252214 Traditional Chinese Medicine Practitioner      230
                  252299 Complementary Health Therapists nec      231
                                    252311 Dental Specialist      232
                                              252312 Dentist      233
                               252411 Occupational Therapist      234
                                      252511 Physiotherapist      235
                                           252611 Podiatrist      236
                                          252711 Audiologist      237
                                   252712 Speech Pathologist      238
                                 253111 General Practitioner      239
                             253112 Resident Medical Officer      240
                                         253211 Anaesthetist      241
              253311 Specialist Physician (General Medicine)      242
                                         253312 Cardiologist      243
                               253313 Clinical Haematologist      244
                                   253314 Medical Oncologist      245
                                      253315 Endocrinologist      246
                                   253316 Gastroenterologist      247
                            253317 Intensive Care Specialist      248
                                          253318 Neurologist      249
                                        253321 Paediatrician      250
                            253322 Renal Medicine Specialist      251
                         253324 Thoracic Medicine Specialist      252
                            253399 Specialist Physicians nec      253
                                         253411 Psychiatrist      254
                                    253511 Surgeon (General)      255
                               253512 Cardiothoracic Surgeon      256
                                         253513 Neurosurgeon      257
                                  253514 Orthopaedic Surgeon      258
                                   253516 Paediatric Surgeon      259
                   253517 Plastic and Reconstructive Surgeon      260
                                            253518 Urologist      261
                                     253521 Vascular Surgeon      262
                                        253911 Dermatologist      263
                        253912 Emergency Medicine Specialist      264
                       253913 Obstetrician and Gynaecologist      265
                                      253914 Ophthalmologist      266
                                          253915 Pathologist      267
            253917 Diagnostic and Interventional Radiologist      268
                                 253918 Radiation Oncologist      269
                            253999 Medical Practitioners nec      270
                                              254111 Midwife      271
                                       254211 Nurse Educator      272
                                     254212 Nurse Researcher      273
                                        254311 Nurse Manager      274
                                   254411 Nurse Practitioner      275
                         254412 Registered Nurse (Aged Care)      276
           254413 Registered Nurse (Child and Family Health)      277
                  254414 Registered Nurse (Community Health)      278
       254415 Registered Nurse (Critical Care and Emergency)      279
          254416 Registered Nurse (Developmental Disability)      280
     254417 Registered Nurse (Disability and Rehabilitation)      281
                           254418 Registered Nurse (Medical)      282
                  254421 Registered Nurse (Medical Practice)      283

In [43]:
occ_dict = dict(zip(mapping["occupation"], mapping["encoded"]))

# ── Input ───────────────────────────────────────────────────
occupation_name = "233211 Civil Engineer"
English = 10
eoi_count = 499
state = "TAS"
visa_type = "190"  # "189", "190", atau "491"

# ── Mapping ─────────────────────────────────────────────────
STATE_COL_MAP = {
    "ACT": "State_ACT",
    "NSW": "State_NSW",
    "NT": "State_NT",
    "QLD": "State_QLD",
    "SA": "State_SA",
    "TAS": "State_TAS",
    "VIC": "State_VIC",
    "WA": "State_WA",
}

VISA_COL_MAP = {
    "189": "Visa Type_189SS Skilled Independent",  # ← sesuaikan nama kolom
    "190": "Visa Type_190SAS Skilled Australian Sponsored",
    "491": "Visa Type_491SNR State or Territory - Regional",
}

# ── Validasi input awal ──────────────────────────────────────
if state not in STATE_COL_MAP:
    raise ValueError(
        f"State '{state}' tidak valid! Pilih: {list(STATE_COL_MAP.keys())}"
    )

if visa_type not in VISA_COL_MAP:
    raise ValueError(
        f"Visa type '{visa_type}' tidak valid! Pilih: {list(VISA_COL_MAP.keys())}"
    )

# ── Encode occupation ────────────────────────────────────────
if occupation_name not in le_occ.classes_:
    raise ValueError(
        f"Occupation '{occupation_name}' tidak ditemukan di label encoder!"
    )

occ_enc = int(le_occ.transform([occupation_name])[0])

# ── Buat data dummy ──────────────────────────────────────────
data_dummy = pd.DataFrame(0, index=[0], columns=X_train.columns)
data_dummy["Count EOIs"] = eoi_count
data_dummy["occupation_enc"] = occ_enc
data_dummy['English Test Score'] = English

# Set State — FIX: sekarang pakai variabel state, bukan hardcode
state_col = STATE_COL_MAP[state]
if state_col in data_dummy.columns:
    data_dummy[state_col] = 1
else:
    print(f"⚠️  Kolom '{state_col}' tidak ada di training data!")

# Set Visa Type
visa_col = VISA_COL_MAP[visa_type]
if visa_col in data_dummy.columns:
    data_dummy[visa_col] = 1
else:
    print(f"⚠️  Kolom '{visa_col}' tidak ada di training data!")
    print(
        f"    Kolom visa yang tersedia: {[c for c in X_train.columns if 'Visa' in c]}"
    )

data_dummy = data_dummy.astype(float)

# ── Debug — cek kolom yang aktif ────────────────────────────
print("Kolom aktif (non-zero):")
print(data_dummy.loc[:, data_dummy.iloc[0] != 0].T.to_string())
print()

# ── Prediksi ─────────────────────────────────────────────────
prediksi_label = model.predict(data_dummy)[0]
prediksi_proba = model.predict_proba(data_dummy)[0]

status_map = {0: "NOT LODGED", 1: "LODGED"}
status = status_map.get(prediksi_label, str(prediksi_label))

# ── Output ───────────────────────────────────────────────────
print("=" * 55)
print("  HASIL PREDIKSI")
print("=" * 55)
print(f"  Occupation    : {occupation_name}")
print(f"  EOI Count     : {eoi_count}")
print(f"  State         : {state}")
print(f"  Visa Type     : {visa_type}")
print(f"  {'─' * 37}")
print(f"  Prediksi      : {status}")
print(f"  P(NOT LODGED) : {prediksi_proba[0] * 100:.2f}%")
print(f"  P(LODGED)     : {prediksi_proba[1] * 100:.2f}%")
print("=" * 55)

Kolom aktif (non-zero):
                                                   0
Count EOIs                                     499.0
English Test Score                              10.0
Visa Type_190SAS Skilled Australian Sponsored    1.0
State_TAS                                        1.0
occupation_enc                                 146.0

=======================================================
  HASIL PREDIKSI
=======================================================
  Occupation    : 233211 Civil Engineer
  EOI Count     : 499
  State         : TAS
  Visa Type     : 190
  ─────────────────────────────────────
  Prediksi      : NOT LODGED
  P(NOT LODGED) : 69.79%
  P(LODGED)     : 30.21%
=======================================================

In [50]:
# ── Cek balance per kombinasi occupation & english score ─────
print("=" * 60)
print("  CEK BALANCE PER KOMBINASI OCCUPATION & ENGLISH SCORE")
print("=" * 60)

# 1. Hitung distribusi per kombinasi
combo_stats = (
    df_model.groupby(["occupation_enc", "English Test Score"])["Status_enc"]
    .agg(lodged="sum", total="count")
    .reset_index()
)
combo_stats["not_lodged"] = combo_stats["total"] - combo_stats["lodged"]
combo_stats["lodged_pct"] = combo_stats["lodged"] / combo_stats["total"] * 100

print(f"\nTotal kombinasi unik : {len(combo_stats):,}")
print(
    f"Kombinasi yg HANYA NOT LODGED (lodged=0) : {(combo_stats['lodged'] == 0).sum():,}"
)
print(
    f"Kombinasi yg HANYA LODGED (not_lodged=0) : {(combo_stats['not_lodged'] == 0).sum():,}"
)
print(
    f"Kombinasi yg balance (40-60%) : {combo_stats['lodged_pct'].between(40, 60).sum():,}"
)

print(f"\nDistribusi LODGED rate per kombinasi:")
print(combo_stats["lodged_pct"].describe().round(2))

============================================================
  CEK BALANCE PER KOMBINASI OCCUPATION & ENGLISH SCORE
============================================================

Total kombinasi unik : 1,444
Kombinasi yg HANYA NOT LODGED (lodged=0) : 200
Kombinasi yg HANYA LODGED (not_lodged=0) : 138
Kombinasi yg balance (40-60%) : 809

Distribusi LODGED rate per kombinasi:
count    1444.00
mean       48.13
std        25.87
min         0.00
25%        41.99
50%        50.00
75%        58.14
max       100.00
Name: lodged_pct, dtype: float64

In [102]:
# Ganti sesuai Occupation & state yang dimaksud
occ_name = "231114 Helicopter Pilot"  # ← ganti
state_name = "WA"  # ← ganti

# ── Cek di data mentah ───────────────────────────────────────
print("=" * 60)
print(f"  CEK: {occ_name} | {state_name}")
print("=" * 60)

# 1. Overall Occupation
occ_data = df_clean[df_clean["Occupation"] == occ_name]
print(f"\n[1] Overall Occupation:")
print(f"    Total baris : {len(occ_data):,}")
print(f"    LODGED      : {(occ_data['EOI Status'] == 'LODGED').sum():,}")
print(f"    NOT LODGED  : {(occ_data['EOI Status'] == 'NOT LODGED').sum():,}")

# 2. Occupation di state tersebut
occ_state = df_clean[
    (df_clean["Occupation"] == occ_name) & (df_clean["State"] == state_name)
]
print(f"\n[2] OccuState {state_name}:")
print(f"    Total baris : {len(occ_state):,}")
print(f"    LODGED      : {(occ_state['EOI Status'] == 'LODGED').sum():,}")
print(f"    NOT LODGED  : {(occ_state['EOI Status'] == 'NOT LODGED').sum():,}")


# 4. Distribusi English Score
print(f"\n[4] Distribusi English Score di {state_name}:")
print(occ_state.groupby("EOI Status")["English Test Score"].value_counts())

# 5. Cek berapa baris total — kalau sedikit = overfitting!
print(f"\n[5] Sample data di {state_name}:")
print(
    occ_state[
        ["Occupation", "State",  "English Test Score", "EOI Status"]
    ]
    .head(10)
    .to_string(index=False)
)

============================================================
  CEK: 231114 Helicopter Pilot | WA
============================================================

[1] Overall Occupation:
    Total baris : 0
    LODGED      : 0
    NOT LODGED  : 0

[2] OccuState WA:
    Total baris : 0
    LODGED      : 0
    NOT LODGED  : 0

[4] Distribusi English Score di WA:
Series([], Name: count, dtype: int64)

[5] Sample data di WA:
Empty DataFrame
Columns: [Occupation, State, English Test Score, EOI Status]
Index: []

In [72]:
model.save_model("model_xgboost.json")